package ng.csp.api.evidence;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import ng.csp.api.web.ApiException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Evidence on the local disk, for development.
 *
 * <p>Not object storage: no encryption at rest, no object lock, no retention, and it lives on one
 * machine. It exists so that the claim path — report a death, attach a certificate, have an assessor
 * read it — works on a laptop with nothing installed, which is the only way that path gets tested
 * before a bucket exists. The prod profile refuses to start on it.
 *
 * <p>Uploads come back through this service rather than to a bucket, so {@link #begin} hands out
 * this service's own endpoint. That is the one behavioural difference from S3 and it is contained
 * here: the client follows the URL it is given either way.
 */
public class LocalEvidence implements Evidence {

  private static final Logger log = LoggerFactory.getLogger(LocalEvidence.class);

  private final Path root;
  private final String baseUrl;

  public LocalEvidence(Path root, String baseUrl) {
    this.root = root.toAbsolutePath().normalize();
    this.baseUrl = baseUrl.replaceAll("/$", "");
    try {
      Files.createDirectories(this.root);
    } catch (IOException e) {
      throw new IllegalStateException("Could not create the evidence directory at " + this.root, e);
    }
  }

  @Override
  public Upload begin(String key, String contentType, long byteSize) {
    return new Upload(
        key,
        "%s/v1/evidence/%s".formatted(baseUrl, key),
        "PUT",
        Map.of("Content-Type", contentType),
        // Matches the S3 presigner's window, so a client written against one
        // does not discover a different timeout against the other.
        Instant.now().plus(Duration.ofMinutes(15)));
  }

  /** Writes the bytes, having first checked the key cannot walk out of the directory. */
  public void write(String key, InputStream body) {
    var file = resolve(key);
    try {
      Files.createDirectories(file.getParent());
      // Replacing, because a retried PUT after a dropped connection is a normal
      // thing for a browser to do and should not come back as a 500.
      Files.copy(body, file, StandardCopyOption.REPLACE_EXISTING);
    } catch (IOException e) {
      throw new IllegalStateException("Could not store evidence " + key, e);
    }
  }

  @Override
  public void put(String key, String contentType, Path file) {
    var target = resolve(key);
    try {
      Files.createDirectories(target.getParent());
      Files.copy(file, target, StandardCopyOption.REPLACE_EXISTING);
    } catch (IOException e) {
      throw new IllegalStateException("Could not store " + key, e);
    }
  }

  @Override
  public InputStream read(String key) {
    try {
      return Files.newInputStream(resolve(key));
    } catch (IOException e) {
      throw ApiException.notFound("That document has not been uploaded.");
    }
  }

  @Override
  public boolean exists(String key) {
    return Files.isRegularFile(resolve(key));
  }

  @Override
  public String describe() {
    return "local directory " + root;
  }

  /**
   * A key to a path under the root, and nowhere else.
   *
   * <p>Keys are generated by this service and not by callers, so this should never fire — which is
   * exactly why it is here. The day somebody adds a path the client supplies, "../../etc/passwd"
   * stops being a hypothetical.
   */
  private Path resolve(String key) {
    var file = root.resolve(key).normalize();
    if (!file.startsWith(root)) {
      log.error("evidence key escaped the root: {}", key);
      throw ApiException.badRequest("That is not a document key.");
    }
    return file;
  }
}
