/*
 * Spring Batch's own tables, and the staging table the schedule load works
 * through.
 *
 * Batch's schema is applied by Flyway rather than by
 * `spring.batch.jdbc.initialize-schema`, because two things creating tables in
 * one database is how a migration history stops describing what is actually
 * there. The body below is Batch's published PostgreSQL script, unedited.
 */

-- Autogenerated: do not edit this file

CREATE TABLE BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME VARCHAR(100) NOT NULL,
	PARAMETER_TYPE VARCHAR(100) NOT NULL,
	PARAMETER_VALUE VARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_INSTANCE_SEQ MAXVALUE 9223372036854775807 NO CYCLE;


/*
 * Where a payroll schedule lands before it becomes money.
 *
 * The old loader did a SELECT and an INSERT per row inside one transaction:
 * about seventeen thousand round trips for a federal schedule of 8,412, and
 * simply impossible at the million rows the build spec asks for. Worse, a
 * failure at row 900,000 rolled back all of it, so a bad file cost the whole
 * load rather than the rows that were wrong.
 *
 * So rows are written here first — a bulk insert, no lookups — and matched and
 * loaded by set-based statements inside chunked steps. The staging row is also
 * what makes a rejection reportable: "line 4,412: no member with service number
 * 8812441" needs the line number kept, which a straight insert-or-skip throws
 * away.
 */
CREATE TYPE schedule_row_state AS ENUM ('staged', 'matched', 'loaded', 'rejected');

CREATE TABLE schedule_rows (
  id            bigserial PRIMARY KEY,
  batch_id      uuid        NOT NULL REFERENCES schedule_batches (id) ON DELETE CASCADE,
  line_no       integer     NOT NULL,
  service_no    text        NOT NULL,
  full_name     text,
  amount_minor  bigint      NOT NULL CHECK (amount_minor >= 0),
  member_id     uuid        REFERENCES members (id),
  state         schedule_row_state NOT NULL DEFAULT 'staged',
  reason        text,
  UNIQUE (batch_id, line_no)
);

/* The two scans the job does: "what is still staged" and "what was rejected". */
CREATE INDEX schedule_rows_work ON schedule_rows (batch_id, state, id);

/*
 * Progress, so the console can say "412,000 of 1,000,000" rather than spinning.
 *
 * Kept on the batch rather than derived by counting staging rows, because
 * counting a million-row table every time somebody refreshes a page is its own
 * outage.
 */
ALTER TABLE schedule_batches
  ADD COLUMN state          text NOT NULL DEFAULT 'complete',
  ADD COLUMN staged_count   integer NOT NULL DEFAULT 0,
  ADD COLUMN matched_count  integer NOT NULL DEFAULT 0,
  ADD COLUMN loaded_count   integer NOT NULL DEFAULT 0,
  ADD COLUMN started_at     timestamptz,
  ADD COLUMN finished_at    timestamptz,
  ADD COLUMN failure        text;

/* Existing rows predate the job and are, by definition, already done. */
ALTER TABLE schedule_batches ALTER COLUMN state SET DEFAULT 'staged';
